### ISSUE TITLE
好像运行有问题

### ISSUE THREAD

**Issue by hacken156026692** [shuye73/xmly#1]
同步仓库，新建PAT、XMLY_SPEED_COOKIE后，star，发现action有问题，红色x，显示如下

The job was not started because there was a billing issue. Please check the 'Billing and plans' section in your settings.
repo-sync
Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see https://github.com/actions/virtual-environments/issues/1816

**Comment by shuye73** [comment]
我看下

**Comment by shuye73** [comment]
试了没问题，

**Comment by hacken156026692** [comment]
> 试了没问题，

大佬，我知道为什么出错了，我设置了private，我改成public后，同步正常了！！
